// Package executor provides safe command execution for LuciCodex.
//
// The executor package handles running shell commands generated by the LLM
// with proper timeout handling, output limiting, and error recovery.
//
// Key features:
//   - Safe command execution with minimal environment (PATH only)
//   - Per-command timeout enforcement
//   - Output size limiting to prevent memory exhaustion
//   - Streaming output support for real-time feedback
//   - Automatic retry with AI-generated fixes
//   - Memory-efficient string builder pooling
//
// Example usage:
//
//	cfg := config.Load("")
//	engine := executor.New(cfg)
//	results := engine.RunPlan(ctx, plan)
//	for _, r := range results.Items {
//	    fmt.Printf("Command %d: %v\n", r.Index, r.Err)
//	}
package executor
